//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Block()
        {
            this.Parkings = new HashSet<Parking>();
        }
    
        public long b_code { get; set; }
        public long b_parkingLotCode { get; set; }
        public long b_numberParkingsForI { get; set; }
        public long b_numberParkingsForJ { get; set; }
        public long b_legalParkings { get; set; }
        public string b_enteranceDirection { get; set; }
        public Nullable<long> b_codeName { get; set; }
    
        public virtual ParkingLot ParkingLot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parking> Parkings { get; set; }
    }
}
