//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parking()
        {
            this.UsingParkings = new HashSet<UsingParking>();
        }
    
        public long p_code { get; set; }
        public long p_parkingLotCode { get; set; }
        public long p_Location_i { get; set; }
        public long p_Location_j { get; set; }
        public bool p_isLegal { get; set; }
        public string p_status { get; set; }
        public long p_blockNumber { get; set; }
        public string p_name { get; set; }
    
        public virtual Block Block { get; set; }
        public virtual ParkingLot ParkingLot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsingParking> UsingParkings { get; set; }
    }
}
