//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermanentUser
    {
        public long cu_code { get; set; }
        public long cu_userCode { get; set; }
        public long cu_parkingLotCode { get; set; }
        public int cu_dayCode { get; set; }
        public System.DateTime cu_entranceHour { get; set; }
        public System.DateTime cu_leavingHour { get; set; }
        public System.DateTime cu_startDate { get; set; }
        public System.DateTime cu_lastDate { get; set; }
        public bool cu_status { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual ParkingLot ParkingLot { get; set; }
        public virtual User User { get; set; }
    }
}
