//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.ParkingLots = new HashSet<ParkingLot>();
            this.PermanentUsers = new HashSet<PermanentUser>();
        }
    
        public long u_code { get; set; }
        public string u_id { get; set; }
        public string u_firstName { get; set; }
        public string u_lastName { get; set; }
        public int u_permission { get; set; }
        public string u_password { get; set; }
        public string u_Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParkingLot> ParkingLots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermanentUser> PermanentUsers { get; set; }
        public virtual UserPermission UserPermission { get; set; }
    }
}
