//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsingParking
    {
        public long up_code { get; set; }
        public long up_parkingCode { get; set; }
        public System.DateTime up_date { get; set; }
        public System.DateTime up_entranceHour { get; set; }
        public System.DateTime up_leavingHour { get; set; }
        public bool up_isUsing { get; set; }
    
        public virtual Parking Parking { get; set; }
    }
}
